// Shared generation logic for @cmux/core-types.
//
// Invokes `cargo test -p cmux-core --features ts` with TS_RS_EXPORT_DIR pointed
// at a destination directory. ts-rs writes one `<Type>.ts` per #[ts(export)]
// type plus the hand-written union binding and barrel `index.ts` (see the
// `ts_export` test in crates/cmux-core/src/session.rs).
//
// Runtime-agnostic: uses only `node:*` builtins, so it runs under both `bun`
// and `node`.
import { execFileSync } from "node:child_process";
import {
  cpSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
// scripts/ -> core-types -> packages -> desktop -> apps -> <repo root>
export const PKG_DIR = resolve(HERE, "..");
export const REPO_ROOT = resolve(PKG_DIR, "..", "..", "..", "..");
export const GENERATED_DIR = join(PKG_DIR, "src", "generated");

const HEADER =
  "// AUTO-GENERATED by @cmux/core-types from crates/cmux-core (ts-rs).\n" +
  "// Do not edit by hand. Run `bun run generate` to refresh.\n";

/**
 * Run the Rust ts-rs export into `outDir`. Returns the sorted list of file names.
 */
export function exportInto(outDir) {
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });

  execFileSync(
    "cargo",
    ["test", "-p", "cmux-core", "--features", "ts", "--quiet"],
    {
      cwd: REPO_ROOT,
      env: { ...process.env, TS_RS_EXPORT_DIR: outDir },
      stdio: ["ignore", "inherit", "inherit"],
    },
  );

  // Normalize the ts-rs file header so generated files carry a clear
  // "do not edit" banner that is stable across ts-rs versions.
  const files = readdirSync(outDir).filter((f) => f.endsWith(".ts")).sort();
  for (const f of files) {
    const p = join(outDir, f);
    const body = readFileSync(p, "utf8").replace(
      /^\/\/ This file was generated by[^\n]*\n/,
      "",
    );
    writeFileSync(p, HEADER + body);
  }
  return files;
}

/** Generate straight into the committed `src/generated` directory. */
export function generateCommitted() {
  const files = exportInto(GENERATED_DIR);
  return files;
}

/** Generate into a fresh temp dir and return its path + file list. */
export function generateTemp() {
  const dir = mkdtempSync(join(tmpdir(), "cmux-core-types-"));
  const files = exportInto(dir);
  return { dir, files };
}

export { cpSync, readFileSync, readdirSync, rmSync };
