// Shared generation logic for @cmux/core-types.
//
// Invokes `cargo test -p <crate> --features ts` for every crate in `CRATES`
// with TS_RS_EXPORT_DIR pointed at one shared destination directory. ts-rs
// writes one `<Type>.ts` per #[ts(export)] type (cmux-core additionally writes
// the hand-written union binding via the `ts_export` test in
// crates/cmux-core/src/session.rs). The barrel `index.ts` is then assembled
// here in JS from the generated file listing, so it always covers every
// exported type across all crates regardless of which crate emitted it.
//
// Runtime-agnostic: uses only `node:*` builtins, so it runs under both `bun`
// and `node`.
import { execFileSync } from "node:child_process";
import {
  cpSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
// scripts/ -> core-types -> packages -> desktop -> apps -> <repo root>
export const PKG_DIR = resolve(HERE, "..");
export const REPO_ROOT = resolve(PKG_DIR, "..", "..", "..", "..");
export const GENERATED_DIR = join(PKG_DIR, "src", "generated");

// Crates whose #[ts(export)] serde models feed the @cmux/core-types bindings.
// Each is exported into the same TS_RS_EXPORT_DIR; type names are disjoint
// across crates so the flat output directory needs no per-crate namespacing.
const CRATES = ["cmux-core", "cmux-config", "cmux-agent-chat", "cmux-diff"];

const HEADER =
  "// AUTO-GENERATED by @cmux/core-types from the cmux Rust crates (ts-rs).\n" +
  "// Do not edit by hand. Run `bun run generate` to refresh.\n";

/**
 * Run the Rust ts-rs export for every crate into `outDir`, then (re)build the
 * barrel `index.ts` from the generated file listing. Returns the sorted list
 * of file names.
 */
export function exportInto(outDir) {
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });
  // ts-rs emits non-actionable diagnostics for supported serde
  // `skip_serializing_if` attributes. Strict Rust/Clippy gates run separately;
  // keep binding generation deterministic and warning-free.
  const rustflags = [process.env.RUSTFLAGS, "-Awarnings"].filter(Boolean).join(" ");

  for (const crate of CRATES) {
    execFileSync(
      "cargo",
      ["test", "-p", crate, "--features", "ts", "--quiet"],
      {
        cwd: REPO_ROOT,
        env: { ...process.env, RUSTFLAGS: rustflags, TS_RS_EXPORT_DIR: outDir },
        // Cargo's successful ts-rs export emits known serde-parser diagnostics
        // on stderr. Keep successful generation warning-free; execFileSync
        // still includes captured stderr when a command fails.
        stdio: ["ignore", "inherit", "pipe"],
      },
    );
  }

  // Normalize the ts-rs file header so generated files carry a clear
  // "do not edit" banner that is stable across ts-rs versions. The barrel
  // `index.ts` (written by the cmux-core test) is regenerated below to cover
  // every crate, so exclude it from header normalization here.
  const typeFiles = readdirSync(outDir)
    .filter((f) => f.endsWith(".ts") && f !== "index.ts")
    .sort();
  for (const f of typeFiles) {
    const p = join(outDir, f);
    const body = readFileSync(p, "utf8")
      .replace(/^\/\/ This file was generated by[^\n]*\n/, "")
      .replace(/[ \t]+$/gm, "");
    writeFileSync(p, HEADER + body);
  }

  // Assemble the barrel from the generated type files so it always re-exports
  // every #[ts(export)] type across all crates in CRATES.
  const barrel =
    HEADER +
    typeFiles
      .map((f) => {
        const name = f.slice(0, -3);
        return `export type { ${name} } from "./${name}";\n`;
      })
      .join("");
  writeFileSync(join(outDir, "index.ts"), barrel);

  return [...typeFiles, "index.ts"].sort();
}

/** Generate straight into the committed `src/generated` directory. */
export function generateCommitted() {
  const files = exportInto(GENERATED_DIR);
  return files;
}

/** Generate into a fresh temp dir and return its path + file list. */
export function generateTemp() {
  const dir = mkdtempSync(join(tmpdir(), "cmux-core-types-"));
  const files = exportInto(dir);
  return { dir, files };
}

export { cpSync, readFileSync, readdirSync, rmSync };
