// @generated by crates/cmux-core/scripts/extract_action_enum.py
// Source of truth: Sources/KeyboardShortcutSettings.swift (enum Action: String)
//
// DO NOT EDIT BY HAND. Every variant's serde rename is an on-disk config key
// persisted in cmux.json; a typo silently breaks config compatibility. To change
// the catalog, edit the Swift source and re-run the extraction script.

use serde::{Deserialize, Serialize};

/// Keyboard-shortcut action identifiers, ported 1:1 from the Swift
/// `KeyboardShortcutSettings.Action` enum. Each variant serializes to the exact
/// String raw value used on disk in `cmux.json`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "openSettings")]
    OpenSettings,
    #[serde(rename = "reloadConfiguration")]
    ReloadConfiguration,
    #[serde(rename = "showHideAllWindows")]
    ShowHideAllWindows,
    #[serde(rename = "globalSearch")]
    GlobalSearch,
    #[serde(rename = "newWindow")]
    NewWindow,
    #[serde(rename = "closeWindow")]
    CloseWindow,
    #[serde(rename = "toggleFullScreen")]
    ToggleFullScreen,
    #[serde(rename = "quit")]
    Quit,
    #[serde(rename = "toggleSidebar")]
    ToggleSidebar,
    #[serde(rename = "newTab")]
    NewTab,
    #[serde(rename = "newBrowserWorkspace")]
    NewBrowserWorkspace,
    #[serde(rename = "openFolder")]
    OpenFolder,
    #[serde(rename = "reopenPreviousSession")]
    ReopenPreviousSession,
    #[serde(rename = "goToWorkspace")]
    GoToWorkspace,
    #[serde(rename = "commandPalette")]
    CommandPalette,
    #[serde(rename = "commandPaletteNext")]
    CommandPaletteNext,
    #[serde(rename = "commandPalettePrevious")]
    CommandPalettePrevious,
    #[serde(rename = "sendFeedback")]
    SendFeedback,
    #[serde(rename = "showNotifications")]
    ShowNotifications,
    #[serde(rename = "jumpToUnread")]
    JumpToUnread,
    #[serde(rename = "toggleUnread")]
    ToggleUnread,
    #[serde(rename = "markOldestUnreadAndJumpNext")]
    MarkOldestUnreadAndJumpNext,
    #[serde(rename = "focusRightSidebar")]
    FocusRightSidebar,
    #[serde(rename = "switchRightSidebarToFiles")]
    SwitchRightSidebarToFiles,
    #[serde(rename = "switchRightSidebarToFind")]
    SwitchRightSidebarToFind,
    #[serde(rename = "switchRightSidebarToSessions")]
    SwitchRightSidebarToSessions,
    #[serde(rename = "switchRightSidebarToFeed")]
    SwitchRightSidebarToFeed,
    #[serde(rename = "switchRightSidebarToDock")]
    SwitchRightSidebarToDock,
    #[serde(rename = "triggerFlash")]
    TriggerFlash,
    #[serde(rename = "nextSurface")]
    NextSurface,
    #[serde(rename = "prevSurface")]
    PrevSurface,
    #[serde(rename = "selectSurfaceByNumber")]
    SelectSurfaceByNumber,
    #[serde(rename = "nextSidebarTab")]
    NextSidebarTab,
    #[serde(rename = "prevSidebarTab")]
    PrevSidebarTab,
    #[serde(rename = "focusHistoryBack")]
    FocusHistoryBack,
    #[serde(rename = "focusHistoryForward")]
    FocusHistoryForward,
    #[serde(rename = "selectWorkspaceByNumber")]
    SelectWorkspaceByNumber,
    #[serde(rename = "renameTab")]
    RenameTab,
    #[serde(rename = "renameWorkspace")]
    RenameWorkspace,
    #[serde(rename = "editWorkspaceDescription")]
    EditWorkspaceDescription,
    #[serde(rename = "closeTab")]
    CloseTab,
    #[serde(rename = "closeOtherTabsInPane")]
    CloseOtherTabsInPane,
    #[serde(rename = "closeWorkspace")]
    CloseWorkspace,
    #[serde(rename = "groupSelectedWorkspaces")]
    GroupSelectedWorkspaces,
    #[serde(rename = "toggleFocusedWorkspaceGroupCollapsed")]
    ToggleFocusedWorkspaceGroupCollapsed,
    #[serde(rename = "reopenClosedBrowserPanel")]
    ReopenClosedBrowserPanel,
    #[serde(rename = "newSurface")]
    NewSurface,
    #[serde(rename = "toggleTerminalCopyMode")]
    ToggleTerminalCopyMode,
    #[serde(rename = "focusTextBoxInput")]
    FocusTextBoxInput,
    #[serde(rename = "attachTextBoxFile")]
    AttachTextBoxFile,
    #[serde(rename = "sendCtrlFToTerminal")]
    SendCtrlFToTerminal,
    #[serde(rename = "clearScreenKeepScrollback")]
    ClearScreenKeepScrollback,
    #[serde(rename = "focusLeft")]
    FocusLeft,
    #[serde(rename = "focusRight")]
    FocusRight,
    #[serde(rename = "focusUp")]
    FocusUp,
    #[serde(rename = "focusDown")]
    FocusDown,
    #[serde(rename = "splitRight")]
    SplitRight,
    #[serde(rename = "splitDown")]
    SplitDown,
    #[serde(rename = "toggleSplitZoom")]
    ToggleSplitZoom,
    #[serde(rename = "equalizeSplits")]
    EqualizeSplits,
    #[serde(rename = "splitBrowserRight")]
    SplitBrowserRight,
    #[serde(rename = "splitBrowserDown")]
    SplitBrowserDown,
    #[serde(rename = "toggleCanvasLayout")]
    ToggleCanvasLayout,
    #[serde(rename = "canvasRevealFocusedPane")]
    CanvasRevealFocusedPane,
    #[serde(rename = "canvasOverview")]
    CanvasOverview,
    #[serde(rename = "canvasZoomIn")]
    CanvasZoomIn,
    #[serde(rename = "canvasZoomOut")]
    CanvasZoomOut,
    #[serde(rename = "canvasZoomReset")]
    CanvasZoomReset,
    #[serde(rename = "canvasTidy")]
    CanvasTidy,
    #[serde(rename = "canvasAlignLeft")]
    CanvasAlignLeft,
    #[serde(rename = "canvasAlignRight")]
    CanvasAlignRight,
    #[serde(rename = "canvasAlignTop")]
    CanvasAlignTop,
    #[serde(rename = "canvasAlignBottom")]
    CanvasAlignBottom,
    #[serde(rename = "canvasEqualizeWidths")]
    CanvasEqualizeWidths,
    #[serde(rename = "canvasEqualizeHeights")]
    CanvasEqualizeHeights,
    #[serde(rename = "canvasDistributeHorizontally")]
    CanvasDistributeHorizontally,
    #[serde(rename = "canvasDistributeVertically")]
    CanvasDistributeVertically,
    #[serde(rename = "toggleFileExplorer")]
    ToggleRightSidebar,
    #[serde(rename = "fileExplorerOpenSelection")]
    FileExplorerOpenSelection,
    #[serde(rename = "fileExplorerOpenSelectionFinderAlias")]
    FileExplorerOpenSelectionFinderAlias,
    #[serde(rename = "saveFilePreview")]
    SaveFilePreview,
    #[serde(rename = "openBrowser")]
    OpenBrowser,
    #[serde(rename = "focusBrowserAddressBar")]
    FocusBrowserAddressBar,
    #[serde(rename = "browserBack")]
    BrowserBack,
    #[serde(rename = "browserForward")]
    BrowserForward,
    #[serde(rename = "browserReload")]
    BrowserReload,
    #[serde(rename = "browserHardReload")]
    BrowserHardReload,
    #[serde(rename = "browserZoomIn")]
    BrowserZoomIn,
    #[serde(rename = "browserZoomOut")]
    BrowserZoomOut,
    #[serde(rename = "browserZoomReset")]
    BrowserZoomReset,
    #[serde(rename = "markdownZoomIn")]
    MarkdownZoomIn,
    #[serde(rename = "markdownZoomOut")]
    MarkdownZoomOut,
    #[serde(rename = "markdownZoomReset")]
    MarkdownZoomReset,
    #[serde(rename = "find")]
    Find,
    #[serde(rename = "findInDirectory")]
    FindInDirectory,
    #[serde(rename = "findNext")]
    FindNext,
    #[serde(rename = "findPrevious")]
    FindPrevious,
    #[serde(rename = "hideFind")]
    HideFind,
    #[serde(rename = "useSelectionForFind")]
    UseSelectionForFind,
    #[serde(rename = "toggleBrowserDeveloperTools")]
    ToggleBrowserDeveloperTools,
    #[serde(rename = "showBrowserJavaScriptConsole")]
    ShowBrowserJavaScriptConsole,
    #[serde(rename = "toggleBrowserFocusMode")]
    ToggleBrowserFocusMode,
    #[serde(rename = "toggleReactGrab")]
    ToggleReactGrab,
    #[serde(rename = "openDiffViewer")]
    OpenDiffViewer,
    #[serde(rename = "diffViewerScrollDown")]
    DiffViewerScrollDown,
    #[serde(rename = "diffViewerScrollUp")]
    DiffViewerScrollUp,
    #[serde(rename = "diffViewerScrollToBottom")]
    DiffViewerScrollToBottom,
    #[serde(rename = "diffViewerScrollToTop")]
    DiffViewerScrollToTop,
    #[serde(rename = "diffViewerOpenFileSearch")]
    DiffViewerOpenFileSearch,
}

impl Action {
    /// Total number of variants. Asserted in tests against the Swift case count.
    pub const COUNT: usize = 109;

    /// All variants in Swift source declaration order.
    pub const ALL: [Action; 109] = [
        Action::OpenSettings,
        Action::ReloadConfiguration,
        Action::ShowHideAllWindows,
        Action::GlobalSearch,
        Action::NewWindow,
        Action::CloseWindow,
        Action::ToggleFullScreen,
        Action::Quit,
        Action::ToggleSidebar,
        Action::NewTab,
        Action::NewBrowserWorkspace,
        Action::OpenFolder,
        Action::ReopenPreviousSession,
        Action::GoToWorkspace,
        Action::CommandPalette,
        Action::CommandPaletteNext,
        Action::CommandPalettePrevious,
        Action::SendFeedback,
        Action::ShowNotifications,
        Action::JumpToUnread,
        Action::ToggleUnread,
        Action::MarkOldestUnreadAndJumpNext,
        Action::FocusRightSidebar,
        Action::SwitchRightSidebarToFiles,
        Action::SwitchRightSidebarToFind,
        Action::SwitchRightSidebarToSessions,
        Action::SwitchRightSidebarToFeed,
        Action::SwitchRightSidebarToDock,
        Action::TriggerFlash,
        Action::NextSurface,
        Action::PrevSurface,
        Action::SelectSurfaceByNumber,
        Action::NextSidebarTab,
        Action::PrevSidebarTab,
        Action::FocusHistoryBack,
        Action::FocusHistoryForward,
        Action::SelectWorkspaceByNumber,
        Action::RenameTab,
        Action::RenameWorkspace,
        Action::EditWorkspaceDescription,
        Action::CloseTab,
        Action::CloseOtherTabsInPane,
        Action::CloseWorkspace,
        Action::GroupSelectedWorkspaces,
        Action::ToggleFocusedWorkspaceGroupCollapsed,
        Action::ReopenClosedBrowserPanel,
        Action::NewSurface,
        Action::ToggleTerminalCopyMode,
        Action::FocusTextBoxInput,
        Action::AttachTextBoxFile,
        Action::SendCtrlFToTerminal,
        Action::ClearScreenKeepScrollback,
        Action::FocusLeft,
        Action::FocusRight,
        Action::FocusUp,
        Action::FocusDown,
        Action::SplitRight,
        Action::SplitDown,
        Action::ToggleSplitZoom,
        Action::EqualizeSplits,
        Action::SplitBrowserRight,
        Action::SplitBrowserDown,
        Action::ToggleCanvasLayout,
        Action::CanvasRevealFocusedPane,
        Action::CanvasOverview,
        Action::CanvasZoomIn,
        Action::CanvasZoomOut,
        Action::CanvasZoomReset,
        Action::CanvasTidy,
        Action::CanvasAlignLeft,
        Action::CanvasAlignRight,
        Action::CanvasAlignTop,
        Action::CanvasAlignBottom,
        Action::CanvasEqualizeWidths,
        Action::CanvasEqualizeHeights,
        Action::CanvasDistributeHorizontally,
        Action::CanvasDistributeVertically,
        Action::ToggleRightSidebar,
        Action::FileExplorerOpenSelection,
        Action::FileExplorerOpenSelectionFinderAlias,
        Action::SaveFilePreview,
        Action::OpenBrowser,
        Action::FocusBrowserAddressBar,
        Action::BrowserBack,
        Action::BrowserForward,
        Action::BrowserReload,
        Action::BrowserHardReload,
        Action::BrowserZoomIn,
        Action::BrowserZoomOut,
        Action::BrowserZoomReset,
        Action::MarkdownZoomIn,
        Action::MarkdownZoomOut,
        Action::MarkdownZoomReset,
        Action::Find,
        Action::FindInDirectory,
        Action::FindNext,
        Action::FindPrevious,
        Action::HideFind,
        Action::UseSelectionForFind,
        Action::ToggleBrowserDeveloperTools,
        Action::ShowBrowserJavaScriptConsole,
        Action::ToggleBrowserFocusMode,
        Action::ToggleReactGrab,
        Action::OpenDiffViewer,
        Action::DiffViewerScrollDown,
        Action::DiffViewerScrollUp,
        Action::DiffViewerScrollToBottom,
        Action::DiffViewerScrollToTop,
        Action::DiffViewerOpenFileSearch,
    ];

    /// The exact on-disk String raw value for this action (matches Swift `rawValue`).
    pub fn raw_value(&self) -> &'static str {
        match self {
            Action::OpenSettings => "openSettings",
            Action::ReloadConfiguration => "reloadConfiguration",
            Action::ShowHideAllWindows => "showHideAllWindows",
            Action::GlobalSearch => "globalSearch",
            Action::NewWindow => "newWindow",
            Action::CloseWindow => "closeWindow",
            Action::ToggleFullScreen => "toggleFullScreen",
            Action::Quit => "quit",
            Action::ToggleSidebar => "toggleSidebar",
            Action::NewTab => "newTab",
            Action::NewBrowserWorkspace => "newBrowserWorkspace",
            Action::OpenFolder => "openFolder",
            Action::ReopenPreviousSession => "reopenPreviousSession",
            Action::GoToWorkspace => "goToWorkspace",
            Action::CommandPalette => "commandPalette",
            Action::CommandPaletteNext => "commandPaletteNext",
            Action::CommandPalettePrevious => "commandPalettePrevious",
            Action::SendFeedback => "sendFeedback",
            Action::ShowNotifications => "showNotifications",
            Action::JumpToUnread => "jumpToUnread",
            Action::ToggleUnread => "toggleUnread",
            Action::MarkOldestUnreadAndJumpNext => "markOldestUnreadAndJumpNext",
            Action::FocusRightSidebar => "focusRightSidebar",
            Action::SwitchRightSidebarToFiles => "switchRightSidebarToFiles",
            Action::SwitchRightSidebarToFind => "switchRightSidebarToFind",
            Action::SwitchRightSidebarToSessions => "switchRightSidebarToSessions",
            Action::SwitchRightSidebarToFeed => "switchRightSidebarToFeed",
            Action::SwitchRightSidebarToDock => "switchRightSidebarToDock",
            Action::TriggerFlash => "triggerFlash",
            Action::NextSurface => "nextSurface",
            Action::PrevSurface => "prevSurface",
            Action::SelectSurfaceByNumber => "selectSurfaceByNumber",
            Action::NextSidebarTab => "nextSidebarTab",
            Action::PrevSidebarTab => "prevSidebarTab",
            Action::FocusHistoryBack => "focusHistoryBack",
            Action::FocusHistoryForward => "focusHistoryForward",
            Action::SelectWorkspaceByNumber => "selectWorkspaceByNumber",
            Action::RenameTab => "renameTab",
            Action::RenameWorkspace => "renameWorkspace",
            Action::EditWorkspaceDescription => "editWorkspaceDescription",
            Action::CloseTab => "closeTab",
            Action::CloseOtherTabsInPane => "closeOtherTabsInPane",
            Action::CloseWorkspace => "closeWorkspace",
            Action::GroupSelectedWorkspaces => "groupSelectedWorkspaces",
            Action::ToggleFocusedWorkspaceGroupCollapsed => "toggleFocusedWorkspaceGroupCollapsed",
            Action::ReopenClosedBrowserPanel => "reopenClosedBrowserPanel",
            Action::NewSurface => "newSurface",
            Action::ToggleTerminalCopyMode => "toggleTerminalCopyMode",
            Action::FocusTextBoxInput => "focusTextBoxInput",
            Action::AttachTextBoxFile => "attachTextBoxFile",
            Action::SendCtrlFToTerminal => "sendCtrlFToTerminal",
            Action::ClearScreenKeepScrollback => "clearScreenKeepScrollback",
            Action::FocusLeft => "focusLeft",
            Action::FocusRight => "focusRight",
            Action::FocusUp => "focusUp",
            Action::FocusDown => "focusDown",
            Action::SplitRight => "splitRight",
            Action::SplitDown => "splitDown",
            Action::ToggleSplitZoom => "toggleSplitZoom",
            Action::EqualizeSplits => "equalizeSplits",
            Action::SplitBrowserRight => "splitBrowserRight",
            Action::SplitBrowserDown => "splitBrowserDown",
            Action::ToggleCanvasLayout => "toggleCanvasLayout",
            Action::CanvasRevealFocusedPane => "canvasRevealFocusedPane",
            Action::CanvasOverview => "canvasOverview",
            Action::CanvasZoomIn => "canvasZoomIn",
            Action::CanvasZoomOut => "canvasZoomOut",
            Action::CanvasZoomReset => "canvasZoomReset",
            Action::CanvasTidy => "canvasTidy",
            Action::CanvasAlignLeft => "canvasAlignLeft",
            Action::CanvasAlignRight => "canvasAlignRight",
            Action::CanvasAlignTop => "canvasAlignTop",
            Action::CanvasAlignBottom => "canvasAlignBottom",
            Action::CanvasEqualizeWidths => "canvasEqualizeWidths",
            Action::CanvasEqualizeHeights => "canvasEqualizeHeights",
            Action::CanvasDistributeHorizontally => "canvasDistributeHorizontally",
            Action::CanvasDistributeVertically => "canvasDistributeVertically",
            Action::ToggleRightSidebar => "toggleFileExplorer",
            Action::FileExplorerOpenSelection => "fileExplorerOpenSelection",
            Action::FileExplorerOpenSelectionFinderAlias => "fileExplorerOpenSelectionFinderAlias",
            Action::SaveFilePreview => "saveFilePreview",
            Action::OpenBrowser => "openBrowser",
            Action::FocusBrowserAddressBar => "focusBrowserAddressBar",
            Action::BrowserBack => "browserBack",
            Action::BrowserForward => "browserForward",
            Action::BrowserReload => "browserReload",
            Action::BrowserHardReload => "browserHardReload",
            Action::BrowserZoomIn => "browserZoomIn",
            Action::BrowserZoomOut => "browserZoomOut",
            Action::BrowserZoomReset => "browserZoomReset",
            Action::MarkdownZoomIn => "markdownZoomIn",
            Action::MarkdownZoomOut => "markdownZoomOut",
            Action::MarkdownZoomReset => "markdownZoomReset",
            Action::Find => "find",
            Action::FindInDirectory => "findInDirectory",
            Action::FindNext => "findNext",
            Action::FindPrevious => "findPrevious",
            Action::HideFind => "hideFind",
            Action::UseSelectionForFind => "useSelectionForFind",
            Action::ToggleBrowserDeveloperTools => "toggleBrowserDeveloperTools",
            Action::ShowBrowserJavaScriptConsole => "showBrowserJavaScriptConsole",
            Action::ToggleBrowserFocusMode => "toggleBrowserFocusMode",
            Action::ToggleReactGrab => "toggleReactGrab",
            Action::OpenDiffViewer => "openDiffViewer",
            Action::DiffViewerScrollDown => "diffViewerScrollDown",
            Action::DiffViewerScrollUp => "diffViewerScrollUp",
            Action::DiffViewerScrollToBottom => "diffViewerScrollToBottom",
            Action::DiffViewerScrollToTop => "diffViewerScrollToTop",
            Action::DiffViewerOpenFileSearch => "diffViewerOpenFileSearch",
        }
    }

    /// Parse an action from its on-disk String raw value.
    pub fn from_raw(raw: &str) -> Option<Action> {
        match raw {
            "openSettings" => Some(Action::OpenSettings),
            "reloadConfiguration" => Some(Action::ReloadConfiguration),
            "showHideAllWindows" => Some(Action::ShowHideAllWindows),
            "globalSearch" => Some(Action::GlobalSearch),
            "newWindow" => Some(Action::NewWindow),
            "closeWindow" => Some(Action::CloseWindow),
            "toggleFullScreen" => Some(Action::ToggleFullScreen),
            "quit" => Some(Action::Quit),
            "toggleSidebar" => Some(Action::ToggleSidebar),
            "newTab" => Some(Action::NewTab),
            "newBrowserWorkspace" => Some(Action::NewBrowserWorkspace),
            "openFolder" => Some(Action::OpenFolder),
            "reopenPreviousSession" => Some(Action::ReopenPreviousSession),
            "goToWorkspace" => Some(Action::GoToWorkspace),
            "commandPalette" => Some(Action::CommandPalette),
            "commandPaletteNext" => Some(Action::CommandPaletteNext),
            "commandPalettePrevious" => Some(Action::CommandPalettePrevious),
            "sendFeedback" => Some(Action::SendFeedback),
            "showNotifications" => Some(Action::ShowNotifications),
            "jumpToUnread" => Some(Action::JumpToUnread),
            "toggleUnread" => Some(Action::ToggleUnread),
            "markOldestUnreadAndJumpNext" => Some(Action::MarkOldestUnreadAndJumpNext),
            "focusRightSidebar" => Some(Action::FocusRightSidebar),
            "switchRightSidebarToFiles" => Some(Action::SwitchRightSidebarToFiles),
            "switchRightSidebarToFind" => Some(Action::SwitchRightSidebarToFind),
            "switchRightSidebarToSessions" => Some(Action::SwitchRightSidebarToSessions),
            "switchRightSidebarToFeed" => Some(Action::SwitchRightSidebarToFeed),
            "switchRightSidebarToDock" => Some(Action::SwitchRightSidebarToDock),
            "triggerFlash" => Some(Action::TriggerFlash),
            "nextSurface" => Some(Action::NextSurface),
            "prevSurface" => Some(Action::PrevSurface),
            "selectSurfaceByNumber" => Some(Action::SelectSurfaceByNumber),
            "nextSidebarTab" => Some(Action::NextSidebarTab),
            "prevSidebarTab" => Some(Action::PrevSidebarTab),
            "focusHistoryBack" => Some(Action::FocusHistoryBack),
            "focusHistoryForward" => Some(Action::FocusHistoryForward),
            "selectWorkspaceByNumber" => Some(Action::SelectWorkspaceByNumber),
            "renameTab" => Some(Action::RenameTab),
            "renameWorkspace" => Some(Action::RenameWorkspace),
            "editWorkspaceDescription" => Some(Action::EditWorkspaceDescription),
            "closeTab" => Some(Action::CloseTab),
            "closeOtherTabsInPane" => Some(Action::CloseOtherTabsInPane),
            "closeWorkspace" => Some(Action::CloseWorkspace),
            "groupSelectedWorkspaces" => Some(Action::GroupSelectedWorkspaces),
            "toggleFocusedWorkspaceGroupCollapsed" => Some(Action::ToggleFocusedWorkspaceGroupCollapsed),
            "reopenClosedBrowserPanel" => Some(Action::ReopenClosedBrowserPanel),
            "newSurface" => Some(Action::NewSurface),
            "toggleTerminalCopyMode" => Some(Action::ToggleTerminalCopyMode),
            "focusTextBoxInput" => Some(Action::FocusTextBoxInput),
            "attachTextBoxFile" => Some(Action::AttachTextBoxFile),
            "sendCtrlFToTerminal" => Some(Action::SendCtrlFToTerminal),
            "clearScreenKeepScrollback" => Some(Action::ClearScreenKeepScrollback),
            "focusLeft" => Some(Action::FocusLeft),
            "focusRight" => Some(Action::FocusRight),
            "focusUp" => Some(Action::FocusUp),
            "focusDown" => Some(Action::FocusDown),
            "splitRight" => Some(Action::SplitRight),
            "splitDown" => Some(Action::SplitDown),
            "toggleSplitZoom" => Some(Action::ToggleSplitZoom),
            "equalizeSplits" => Some(Action::EqualizeSplits),
            "splitBrowserRight" => Some(Action::SplitBrowserRight),
            "splitBrowserDown" => Some(Action::SplitBrowserDown),
            "toggleCanvasLayout" => Some(Action::ToggleCanvasLayout),
            "canvasRevealFocusedPane" => Some(Action::CanvasRevealFocusedPane),
            "canvasOverview" => Some(Action::CanvasOverview),
            "canvasZoomIn" => Some(Action::CanvasZoomIn),
            "canvasZoomOut" => Some(Action::CanvasZoomOut),
            "canvasZoomReset" => Some(Action::CanvasZoomReset),
            "canvasTidy" => Some(Action::CanvasTidy),
            "canvasAlignLeft" => Some(Action::CanvasAlignLeft),
            "canvasAlignRight" => Some(Action::CanvasAlignRight),
            "canvasAlignTop" => Some(Action::CanvasAlignTop),
            "canvasAlignBottom" => Some(Action::CanvasAlignBottom),
            "canvasEqualizeWidths" => Some(Action::CanvasEqualizeWidths),
            "canvasEqualizeHeights" => Some(Action::CanvasEqualizeHeights),
            "canvasDistributeHorizontally" => Some(Action::CanvasDistributeHorizontally),
            "canvasDistributeVertically" => Some(Action::CanvasDistributeVertically),
            "toggleFileExplorer" => Some(Action::ToggleRightSidebar),
            "fileExplorerOpenSelection" => Some(Action::FileExplorerOpenSelection),
            "fileExplorerOpenSelectionFinderAlias" => Some(Action::FileExplorerOpenSelectionFinderAlias),
            "saveFilePreview" => Some(Action::SaveFilePreview),
            "openBrowser" => Some(Action::OpenBrowser),
            "focusBrowserAddressBar" => Some(Action::FocusBrowserAddressBar),
            "browserBack" => Some(Action::BrowserBack),
            "browserForward" => Some(Action::BrowserForward),
            "browserReload" => Some(Action::BrowserReload),
            "browserHardReload" => Some(Action::BrowserHardReload),
            "browserZoomIn" => Some(Action::BrowserZoomIn),
            "browserZoomOut" => Some(Action::BrowserZoomOut),
            "browserZoomReset" => Some(Action::BrowserZoomReset),
            "markdownZoomIn" => Some(Action::MarkdownZoomIn),
            "markdownZoomOut" => Some(Action::MarkdownZoomOut),
            "markdownZoomReset" => Some(Action::MarkdownZoomReset),
            "find" => Some(Action::Find),
            "findInDirectory" => Some(Action::FindInDirectory),
            "findNext" => Some(Action::FindNext),
            "findPrevious" => Some(Action::FindPrevious),
            "hideFind" => Some(Action::HideFind),
            "useSelectionForFind" => Some(Action::UseSelectionForFind),
            "toggleBrowserDeveloperTools" => Some(Action::ToggleBrowserDeveloperTools),
            "showBrowserJavaScriptConsole" => Some(Action::ShowBrowserJavaScriptConsole),
            "toggleBrowserFocusMode" => Some(Action::ToggleBrowserFocusMode),
            "toggleReactGrab" => Some(Action::ToggleReactGrab),
            "openDiffViewer" => Some(Action::OpenDiffViewer),
            "diffViewerScrollDown" => Some(Action::DiffViewerScrollDown),
            "diffViewerScrollUp" => Some(Action::DiffViewerScrollUp),
            "diffViewerScrollToBottom" => Some(Action::DiffViewerScrollToBottom),
            "diffViewerScrollToTop" => Some(Action::DiffViewerScrollToTop),
            "diffViewerOpenFileSearch" => Some(Action::DiffViewerOpenFileSearch),
            _ => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // The Swift source `enum Action: String` declares exactly this many cases.
    // Derived mechanically by the extraction script (see module header) and
    // re-verified below by parsing the Swift file when it is available.
    const SWIFT_CASE_COUNT: usize = 109;

    #[test]
    fn variant_count_matches_swift() {
        assert_eq!(Action::COUNT, SWIFT_CASE_COUNT);
        assert_eq!(Action::ALL.len(), SWIFT_CASE_COUNT);
    }

    #[test]
    fn every_variant_round_trips_via_helpers() {
        for action in Action::ALL {
            let raw = action.raw_value();
            assert_eq!(
                Action::from_raw(raw),
                Some(action),
                "from_raw(raw_value(a)) must equal Some(a) for {action:?}",
            );
        }
    }

    #[test]
    fn every_variant_round_trips_via_serde() {
        for action in Action::ALL {
            // serde serializes a unit variant to a bare JSON string.
            let json = serde_json::to_string(&action).unwrap();
            let expected = format!("\"{}\"", action.raw_value());
            assert_eq!(json, expected, "serde rename must equal raw value for {action:?}");
            let back: Action = serde_json::from_str(&json).unwrap();
            assert_eq!(back, action);
        }
    }

    #[test]
    fn raw_values_are_unique() {
        use std::collections::HashSet;
        let mut seen = HashSet::new();
        for action in Action::ALL {
            assert!(seen.insert(action.raw_value()), "duplicate raw value: {}", action.raw_value());
        }
        assert_eq!(seen.len(), Action::COUNT);
    }

    #[test]
    fn from_raw_rejects_unknown() {
        assert_eq!(Action::from_raw("definitelyNotAnAction"), None);
        assert_eq!(Action::from_raw(""), None);
    }

    #[test]
    fn spot_check_known_raw_values() {
        // Implicit raw values (Swift case name == raw value).
        assert_eq!(Action::OpenSettings.raw_value(), "openSettings");
        assert_eq!(Action::Quit.raw_value(), "quit");
        assert_eq!(Action::SplitDown.raw_value(), "splitDown");
        // Comma-separated sibling on the same Swift `case` line.
        assert_eq!(Action::ToggleSplitZoom.raw_value(), "toggleSplitZoom");
        // Explicit Swift rename: `case toggleRightSidebar = "toggleFileExplorer"`.
        assert_eq!(Action::ToggleRightSidebar.raw_value(), "toggleFileExplorer");
        assert_eq!(Action::from_raw("toggleFileExplorer"), Some(Action::ToggleRightSidebar));
        assert_eq!(Action::from_raw("toggleRightSidebar"), None);
        assert_eq!(Action::DiffViewerOpenFileSearch.raw_value(), "diffViewerOpenFileSearch");
    }

    // When the Swift source is reachable from the test working directory, re-parse
    // it and assert the live case count matches. Skips silently otherwise (e.g. when
    // the crate is built outside the cmux source tree).
    #[test]
    fn swift_source_case_count_matches_if_present() {
        let candidates = [
            "../../Sources/KeyboardShortcutSettings.swift",
            "../Sources/KeyboardShortcutSettings.swift",
            "Sources/KeyboardShortcutSettings.swift",
        ];
        let Some(text) = candidates
            .iter()
            .find_map(|p| std::fs::read_to_string(p).ok())
        else {
            eprintln!("swift source not reachable; skipping live count check");
            return;
        };
        let count = count_swift_action_cases(&text);
        assert_eq!(count, Action::COUNT, "live Swift case count drifted from generated enum");
    }

    /// Count `case` declarations inside the `enum Action: String { ... }` block,
    /// mirroring the extraction script's parsing rules (comma-separated cases,
    /// line comments stripped).
    fn count_swift_action_cases(text: &str) -> usize {
        let lines: Vec<&str> = text.lines().collect();
        let start = lines
            .iter()
            .position(|l| l.contains("enum Action") && l.contains(": String"))
            .expect("enum Action: String not found");
        let mut depth: i32 = 0;
        let mut seen_open = false;
        let mut count = 0usize;
        for line in &lines[start..] {
            for ch in line.chars() {
                if ch == '{' {
                    depth += 1;
                    seen_open = true;
                } else if ch == '}' {
                    depth -= 1;
                }
            }
            let code = line.split("//").next().unwrap_or("").trim();
            // Variant declarations are the leading `case` lines. Stop at the first
            // computed member (`var`/`func`/...), after which `case` lines are
            // `switch` arms (`case .foo:`), not declarations. Mirrors the script.
            if code.starts_with("var ")
                || code.starts_with("func ")
                || code.starts_with("static ")
                || code.starts_with("init")
            {
                break;
            }
            if let Some(rest) = code.strip_prefix("case ") {
                count += rest.split(',').count();
            }
            if seen_open && depth == 0 {
                break;
            }
        }
        count
    }
}
