#!/usr/bin/env python3
"""Mechanically extract the `Action: String` enum cases from the Swift source
and emit the Rust `Action` enum (crates/cmux-core/src/shortcuts_action.rs).

Source of truth:
    Sources/KeyboardShortcutSettings.swift  ->  `enum Action: String, ...`

Why this exists (do NOT hand-retype the raw values):
    Every Action case's String raw value is an on-disk config key persisted in
    `cmux.json`. A rename/typo silently breaks config compatibility. So the raw
    values are extracted mechanically from the Swift file and the Rust enum is
    generated from that extraction.

Parsing rules handled:
    * Implicit raw value: `case foo`              -> rename "foo"  (Swift uses
      the case name as the String raw value).
    * Explicit raw value: `case foo = "bar"`      -> rename "bar".
    * Multiple cases on one line, comma separated:
          `case splitDown, toggleSplitZoom`       -> two cases, each implicit.
      (An explicit `= "..."` may appear on any of the comma-separated items.)
    * Comments (`// ...`) and blank lines inside the enum body are ignored.

Run from the repo root (the worktree root):
    python3 crates/cmux-core/scripts/extract_action_enum.py            # write
    python3 crates/cmux-core/scripts/extract_action_enum.py --check    # verify
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
SWIFT_SRC = REPO_ROOT / "Sources" / "KeyboardShortcutSettings.swift"
RUST_OUT = REPO_ROOT / "crates" / "cmux-core" / "src" / "shortcuts_action.rs"

# Matches a single "name" or "name = \"raw\"" item (one comma-separated piece).
ITEM_RE = re.compile(
    r"""^\s*
        (?P<name>[A-Za-z_][A-Za-z0-9_]*)        # case identifier
        (?:\s*=\s*"(?P<raw>[^"]*)")?            # optional explicit raw value
        \s*$""",
    re.VERBOSE,
)


def upper_camel(name: str) -> str:
    """lowerCamelCase Swift case name -> UpperCamelCase Rust variant."""
    return name[:1].upper() + name[1:]


def extract_cases() -> list[tuple[str, str]]:
    """Return [(swift_case_name, raw_value), ...] in source order."""
    text = SWIFT_SRC.read_text(encoding="utf-8")
    lines = text.splitlines()

    # Locate the `enum Action: String` declaration and its matching close brace
    # by brace-depth tracking from the opening `{`.
    start = None
    for i, line in enumerate(lines):
        if re.search(r"\benum\s+Action\s*:\s*String\b", line):
            start = i
            break
    if start is None:
        raise SystemExit("error: could not find `enum Action: String` in Swift source")

    depth = 0
    seen_open = False
    body: list[str] = []
    for line in lines[start:]:
        for ch in line:
            if ch == "{":
                depth += 1
                seen_open = True
            elif ch == "}":
                depth -= 1
        if seen_open:
            body.append(line)
        if seen_open and depth == 0:
            break

    cases: list[tuple[str, str]] = []
    for line in body:
        # Strip line comments.
        code = line.split("//", 1)[0]
        stripped = code.strip()
        # The variant declarations are the leading `case` lines of the enum
        # body. Once a computed member (`var id`, `var label`, `func ...`) is
        # reached, the remaining `case` lines are `switch` arms (`case .foo:`),
        # not declarations. Stop collecting at the first member keyword.
        if stripped.startswith(("var ", "func ", "static ", "init")):
            break
        if not stripped.startswith("case "):
            continue
        rest = stripped[len("case "):]
        # Split on commas that separate independent cases.
        for piece in rest.split(","):
            m = ITEM_RE.match(piece)
            if not m:
                raise SystemExit(f"error: could not parse case piece: {piece!r} (line: {line!r})")
            name = m.group("name")
            raw = m.group("raw") if m.group("raw") is not None else name
            cases.append((name, raw))
    return cases


def render_rust(cases: list[tuple[str, str]]) -> str:
    n = len(cases)
    out: list[str] = []
    out.append("// @generated by crates/cmux-core/scripts/extract_action_enum.py")
    out.append("// Source of truth: Sources/KeyboardShortcutSettings.swift (enum Action: String)")
    out.append("//")
    out.append("// DO NOT EDIT BY HAND. Every variant's serde rename is an on-disk config key")
    out.append("// persisted in cmux.json; a typo silently breaks config compatibility. To change")
    out.append("// the catalog, edit the Swift source and re-run the extraction script.")
    out.append("")
    out.append("use serde::{Deserialize, Serialize};")
    out.append("")
    out.append("/// Keyboard-shortcut action identifiers, ported 1:1 from the Swift")
    out.append("/// `KeyboardShortcutSettings.Action` enum. Each variant serializes to the exact")
    out.append("/// String raw value used on disk in `cmux.json`.")
    out.append("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]")
    out.append("pub enum Action {")
    for name, raw in cases:
        variant = upper_camel(name)
        out.append(f'    #[serde(rename = "{raw}")]')
        out.append(f"    {variant},")
    out.append("}")
    out.append("")
    out.append("impl Action {")
    out.append("    /// Total number of variants. Asserted in tests against the Swift case count.")
    out.append(f"    pub const COUNT: usize = {n};")
    out.append("")
    out.append("    /// All variants in Swift source declaration order.")
    out.append(f"    pub const ALL: [Action; {n}] = [")
    for name, _raw in cases:
        out.append(f"        Action::{upper_camel(name)},")
    out.append("    ];")
    out.append("")
    out.append("    /// The exact on-disk String raw value for this action (matches Swift `rawValue`).")
    out.append("    pub fn raw_value(&self) -> &'static str {")
    out.append("        match self {")
    for name, raw in cases:
        out.append(f'            Action::{upper_camel(name)} => "{raw}",')
    out.append("        }")
    out.append("    }")
    out.append("")
    out.append("    /// Parse an action from its on-disk String raw value.")
    out.append("    pub fn from_raw(raw: &str) -> Option<Action> {")
    out.append("        match raw {")
    for name, raw in cases:
        out.append(f'            "{raw}" => Some(Action::{upper_camel(name)}),')
    out.append("            _ => None,")
    out.append("        }")
    out.append("    }")
    out.append("}")
    out.append("")
    out.append(render_tests(cases))
    return "\n".join(out) + "\n"


def render_tests(cases: list[tuple[str, str]]) -> str:
    n = len(cases)
    t: list[str] = []
    t.append("#[cfg(test)]")
    t.append("mod tests {")
    t.append("    use super::*;")
    t.append("")
    t.append("    // The Swift source `enum Action: String` declares exactly this many cases.")
    t.append("    // Derived mechanically by the extraction script (see module header) and")
    t.append("    // re-verified below by parsing the Swift file when it is available.")
    t.append(f"    const SWIFT_CASE_COUNT: usize = {n};")
    t.append("")
    t.append("    #[test]")
    t.append("    fn variant_count_matches_swift() {")
    t.append("        assert_eq!(Action::COUNT, SWIFT_CASE_COUNT);")
    t.append("        assert_eq!(Action::ALL.len(), SWIFT_CASE_COUNT);")
    t.append("    }")
    t.append("")
    t.append("    #[test]")
    t.append("    fn every_variant_round_trips_via_helpers() {")
    t.append("        for action in Action::ALL {")
    t.append("            let raw = action.raw_value();")
    t.append("            assert_eq!(")
    t.append("                Action::from_raw(raw),")
    t.append("                Some(action),")
    t.append('                "from_raw(raw_value(a)) must equal Some(a) for {action:?}",')
    t.append("            );")
    t.append("        }")
    t.append("    }")
    t.append("")
    t.append("    #[test]")
    t.append("    fn every_variant_round_trips_via_serde() {")
    t.append("        for action in Action::ALL {")
    t.append("            // serde serializes a unit variant to a bare JSON string.")
    t.append("            let json = serde_json::to_string(&action).unwrap();")
    t.append('            let expected = format!("\\"{}\\"", action.raw_value());')
    t.append("            assert_eq!(json, expected, \"serde rename must equal raw value for {action:?}\");")
    t.append("            let back: Action = serde_json::from_str(&json).unwrap();")
    t.append("            assert_eq!(back, action);")
    t.append("        }")
    t.append("    }")
    t.append("")
    t.append("    #[test]")
    t.append("    fn raw_values_are_unique() {")
    t.append("        use std::collections::HashSet;")
    t.append("        let mut seen = HashSet::new();")
    t.append("        for action in Action::ALL {")
    t.append("            assert!(seen.insert(action.raw_value()), \"duplicate raw value: {}\", action.raw_value());")
    t.append("        }")
    t.append("        assert_eq!(seen.len(), Action::COUNT);")
    t.append("    }")
    t.append("")
    t.append("    #[test]")
    t.append("    fn from_raw_rejects_unknown() {")
    t.append("        assert_eq!(Action::from_raw(\"definitelyNotAnAction\"), None);")
    t.append('        assert_eq!(Action::from_raw(""), None);')
    t.append("    }")
    t.append("")
    t.append("    #[test]")
    t.append("    fn spot_check_known_raw_values() {")
    t.append("        // Implicit raw values (Swift case name == raw value).")
    t.append('        assert_eq!(Action::OpenSettings.raw_value(), "openSettings");')
    t.append('        assert_eq!(Action::Quit.raw_value(), "quit");')
    t.append('        assert_eq!(Action::SplitDown.raw_value(), "splitDown");')
    t.append("        // Comma-separated sibling on the same Swift `case` line.")
    t.append('        assert_eq!(Action::ToggleSplitZoom.raw_value(), "toggleSplitZoom");')
    t.append("        // Explicit Swift rename: `case toggleRightSidebar = \"toggleFileExplorer\"`.")
    t.append('        assert_eq!(Action::ToggleRightSidebar.raw_value(), "toggleFileExplorer");')
    t.append('        assert_eq!(Action::from_raw("toggleFileExplorer"), Some(Action::ToggleRightSidebar));')
    t.append('        assert_eq!(Action::from_raw("toggleRightSidebar"), None);')
    t.append('        assert_eq!(Action::DiffViewerOpenFileSearch.raw_value(), "diffViewerOpenFileSearch");')
    t.append("    }")
    t.append("")
    t.append("    // When the Swift source is reachable from the test working directory, re-parse")
    t.append("    // it and assert the live case count matches. Skips silently otherwise (e.g. when")
    t.append("    // the crate is built outside the cmux source tree).")
    t.append("    #[test]")
    t.append("    fn swift_source_case_count_matches_if_present() {")
    t.append("        let candidates = [")
    t.append('            "../../Sources/KeyboardShortcutSettings.swift",')
    t.append('            "../Sources/KeyboardShortcutSettings.swift",')
    t.append('            "Sources/KeyboardShortcutSettings.swift",')
    t.append("        ];")
    t.append("        let Some(text) = candidates")
    t.append("            .iter()")
    t.append("            .find_map(|p| std::fs::read_to_string(p).ok())")
    t.append("        else {")
    t.append("            eprintln!(\"swift source not reachable; skipping live count check\");")
    t.append("            return;")
    t.append("        };")
    t.append("        let count = count_swift_action_cases(&text);")
    t.append("        assert_eq!(count, Action::COUNT, \"live Swift case count drifted from generated enum\");")
    t.append("    }")
    t.append("")
    t.append("    /// Count `case` declarations inside the `enum Action: String { ... }` block,")
    t.append("    /// mirroring the extraction script's parsing rules (comma-separated cases,")
    t.append("    /// line comments stripped).")
    t.append("    fn count_swift_action_cases(text: &str) -> usize {")
    t.append("        let lines: Vec<&str> = text.lines().collect();")
    t.append("        let start = lines")
    t.append("            .iter()")
    t.append('            .position(|l| l.contains("enum Action") && l.contains(": String"))')
    t.append('            .expect("enum Action: String not found");')
    t.append("        let mut depth: i32 = 0;")
    t.append("        let mut seen_open = false;")
    t.append("        let mut count = 0usize;")
    t.append("        for line in &lines[start..] {")
    t.append("            for ch in line.chars() {")
    t.append("                if ch == '{' {")
    t.append("                    depth += 1;")
    t.append("                    seen_open = true;")
    t.append("                } else if ch == '}' {")
    t.append("                    depth -= 1;")
    t.append("                }")
    t.append("            }")
    t.append("            let code = line.split(\"//\").next().unwrap_or(\"\").trim();")
    t.append("            // Variant declarations are the leading `case` lines. Stop at the first")
    t.append("            // computed member (`var`/`func`/...), after which `case` lines are")
    t.append("            // `switch` arms (`case .foo:`), not declarations. Mirrors the script.")
    t.append('            if code.starts_with("var ")')
    t.append('                || code.starts_with("func ")')
    t.append('                || code.starts_with("static ")')
    t.append('                || code.starts_with("init")')
    t.append("            {")
    t.append("                break;")
    t.append("            }")
    t.append('            if let Some(rest) = code.strip_prefix("case ") {')
    t.append("                count += rest.split(',').count();")
    t.append("            }")
    t.append("            if seen_open && depth == 0 {")
    t.append("                break;")
    t.append("            }")
    t.append("        }")
    t.append("        count")
    t.append("    }")
    t.append("}")
    return "\n".join(t)


def main() -> int:
    cases = extract_cases()
    rust = render_rust(cases)
    if "--check" in sys.argv:
        existing = RUST_OUT.read_text(encoding="utf-8") if RUST_OUT.exists() else ""
        if existing != rust:
            print("OUT OF DATE: shortcuts_action.rs differs from generated output", file=sys.stderr)
            return 1
        print(f"OK: {len(cases)} cases, generated output matches on disk")
        return 0
    RUST_OUT.write_text(rust, encoding="utf-8")
    print(f"wrote {RUST_OUT} ({len(cases)} variants)")
    # Echo the special-cased (explicit-rename) entries for the report.
    for name, raw in cases:
        if name != raw:
            print(f"  explicit rename: {name} -> \"{raw}\"")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
